// interfaces/actionTypes.ts
// Action type constants for every slice: map, user, message, tool, agent.

const actionTypes = {
  // shared
  SET_ERROR: 'SET_ERROR',

  // map
  SET_MAP: 'SET_MAP',
  CLEAR_MAP: 'CLEAR_MAP',

  // user
  SET_USER: 'SET_USER',
  CLEAR_USER: 'CLEAR_USER',

  // message
  SET_MESSAGES: 'SET_MESSAGES',
  ADD_MESSAGE: 'ADD_MESSAGE',
  CLEAR_MESSAGES: 'CLEAR_MESSAGES',

  // tool
  SET_TOOLS: 'SET_TOOLS',
  ADD_TOOL: 'ADD_TOOL',
  SET_ENABLED_TOOLS: 'SET_ENABLED_TOOLS',
  SET_TOOL_LOADING: 'SET_TOOL_LOADING',
  SET_TOOL_ERROR: 'SET_TOOL_ERROR',
  CLEAR_TOOLS: 'CLEAR_TOOLS',

  // agent
  SET_INSTRUCTION_PRESETS: 'SET_INSTRUCTION_PRESETS',
  ADD_INSTRUCTION_PRESET: 'ADD_INSTRUCTION_PRESET',
  SELECT_INSTRUCTION_PRESET: 'SELECT_INSTRUCTION_PRESET',
  SET_SYSTEM_TEXT: 'SET_SYSTEM_TEXT',
  SET_PROVIDER: 'SET_PROVIDER',
  SET_MODEL: 'SET_MODEL',
  SET_AGENT_ERROR: 'SET_AGENT_ERROR',
  CLEAR_AGENT: 'CLEAR_AGENT',
} as const;

export default actionTypes;
